<?php

// @formatter:off
namespace PHPSTORM_META {
	override(\amis(0), map([
		'form' => \warm\renderer\Form::class,
		'alert' => \warm\renderer\Alert::class,
		'app' => \warm\renderer\Component::class,
		'audio' => \warm\renderer\Audio::class,
		'avatar' => \warm\renderer\Avatar::class,
		'button-group' => \warm\renderer\ButtonGroup::class,
		'breadcrumb' => \warm\renderer\Breadcrumb::class,
		'card' => \warm\renderer\Card::class,
		'card2' => \warm\renderer\Card2::class,
		'cards' => \warm\renderer\Cards::class,
		'carousel' => \warm\renderer\Carousel::class,
		'chart' => \warm\renderer\Chart::class,
		'calendar' => \warm\renderer\Calendar::class,
		'collapse' => \warm\renderer\Collapse::class,
		'collapse-group' => \warm\renderer\CollapseGroup::class,
		'color' => \warm\renderer\Color::class,
		'crud' => \warm\renderer\CRUDTable::class,
		'crud2' => \warm\renderer\CRUD2Table::class,
		'custom' => \warm\renderer\Custom::class,
		'date' => \warm\renderer\Date::class,
		'static-date' => \warm\renderer\StaticExactControl::class,
		'datetime' => \warm\renderer\Date::class,
		'static-datetime' => \warm\renderer\StaticExactControl::class,
		'time' => \warm\renderer\Date::class,
		'static-time' => \warm\renderer\StaticExactControl::class,
		'month' => \warm\renderer\Date::class,
		'static-month' => \warm\renderer\StaticExactControl::class,
		'date-range' => \warm\renderer\DateRange::class,
		'dialog' => \warm\renderer\Dialog::class,
		'spinner' => \warm\renderer\Spinner::class,
		'divider' => \warm\renderer\Divider::class,
		'dropdown-button' => \warm\renderer\DropdownButton::class,
		'drawer' => \warm\renderer\Drawer::class,
		'each' => \warm\renderer\Each::class,
		'flex' => \warm\renderer\Flex::class,
		'flex-item' => \warm\renderer\Component::class,
		'grid-2d' => \warm\renderer\Grid2D::class,
		'icon' => \warm\renderer\Icon::class,
		'iframe' => \warm\renderer\IFrame::class,
		'image' => \warm\renderer\Image::class,
		'static-image' => \warm\renderer\StaticExactControl::class,
		'images' => \warm\renderer\Images::class,
		'static-images' => \warm\renderer\Component::class,
		'json-schema' => \warm\renderer\Json::class,
		'json-schema-editor' => \warm\renderer\JSONSchemaEditorControl::class,
		'json' => \warm\renderer\Json::class,
		'static-json' => \warm\renderer\Component::class,
		'link' => \warm\renderer\Link::class,
		'list' => \warm\renderer\ListRenderer::class,
		'log' => \warm\renderer\Log::class,
		'static-list' => \warm\renderer\Component::class,
		'map' => \warm\renderer\Mapping::class,
		'mapping' => \warm\renderer\Mapping::class,
		'markdown' => \warm\renderer\Markdown::class,
		'nav' => \warm\renderer\Nav::class,
		'number' => \warm\renderer\Component::class,
		'page' => \warm\renderer\Page::class,
		'pagination' => \warm\renderer\Pagination::class,
		'pagination-wrapper' => \warm\renderer\PaginationWrapper::class,
		'property' => \warm\renderer\Property::class,
		'operation' => \warm\renderer\Operation::class,
		'plain' => \warm\renderer\Plain::class,
		'text' => \warm\renderer\Component::class,
		'progress' => \warm\renderer\Progress::class,
		'qrcode' => \warm\renderer\QRCode::class,
		'qr-code' => \warm\renderer\QRCode::class,
		'barcode' => \warm\renderer\Barcode::class,
		'remark' => \warm\renderer\Remark::class,
		'search-box' => \warm\renderer\SearchBox::class,
		'sparkline' => \warm\renderer\SparkLine::class,
		'status' => \warm\renderer\Status::class,
		'table' => \warm\renderer\Table::class,
		'static-table' => \warm\renderer\StaticExactControl::class,
		'table2' => \warm\renderer\TableSchema2::class,
		'html' => \warm\renderer\Html::class,
		'tpl' => \warm\renderer\Tpl::class,
		'tasks' => \warm\renderer\Tasks::class,
		'vbox' => \warm\renderer\VBox::class,
		'video' => \warm\renderer\Video::class,
		'wizard' => \warm\renderer\Wizard::class,
		'wrapper' => \warm\renderer\Wrapper::class,
		'web-component' => \warm\renderer\WebComponent::class,
		'anchor-nav' => \warm\renderer\AnchorNav::class,
		'steps' => \warm\renderer\Steps::class,
		'timeline' => \warm\renderer\Timeline::class,
		'control' => \warm\renderer\FormControl::class,
		'input-array' => \warm\renderer\ArrayControl::class,
		'button' => \warm\renderer\VanillaAction::class,
		'submit' => \warm\renderer\VanillaAction::class,
		'reset' => \warm\renderer\VanillaAction::class,
		'button-group-select' => \warm\renderer\ButtonGroupControl::class,
		'button-toolbar' => \warm\renderer\ButtonToolbar::class,
		'chained-select' => \warm\renderer\ChainedSelectControl::class,
		'chart-radios' => \warm\renderer\ChartRadios::class,
		'checkbox' => \warm\renderer\CheckboxControl::class,
		'checkboxes' => \warm\renderer\CheckboxesControl::class,
		'input-city' => \warm\renderer\InputCityControl::class,
		'input-color' => \warm\renderer\InputColorControl::class,
		'combo' => \warm\renderer\ComboControl::class,
		'condition-builder' => \warm\renderer\ConditionBuilderControl::class,
		'container' => \warm\renderer\Container::class,
		'switch-container' => \warm\renderer\SwitchContainer::class,
		'input-date' => \warm\renderer\DateControl::class,
		'input-datetime' => \warm\renderer\DateTimeControl::class,
		'input-time' => \warm\renderer\TimeControl::class,
		'input-quarter' => \warm\renderer\QuarterControl::class,
		'input-year' => \warm\renderer\YearControl::class,
		'input-month' => \warm\renderer\MonthControl::class,
		'input-date-range' => \warm\renderer\DateRangeControl::class,
		'input-time-range' => \warm\renderer\DateRangeControl::class,
		'input-datetime-range' => \warm\renderer\DateRangeControl::class,
		'input-excel' => \warm\renderer\InputExcel::class,
		'input-formula' => \warm\renderer\Component::class,
		'diff-editor' => \warm\renderer\DiffControl::class,
		'office-viewer' => \warm\renderer\Component::class,
		'pdf-viewer' => \warm\renderer\Component::class,
		'input-signature' => \warm\renderer\InputSignature::class,
        'input-verification-code' => \warm\Renderers\Component::class,
		'editor' => \warm\renderer\EditorControl::class,
		'bat-editor' => \warm\renderer\EditorControl::class,
		'c-editor' => \warm\renderer\EditorControl::class,
		'coffeescript-editor' => \warm\renderer\EditorControl::class,
		'cpp-editor' => \warm\renderer\EditorControl::class,
		'csharp-editor' => \warm\renderer\EditorControl::class,
		'css-editor' => \warm\renderer\EditorControl::class,
		'dockerfile-editor' => \warm\renderer\EditorControl::class,
		'fsharp-editor' => \warm\renderer\EditorControl::class,
		'go-editor' => \warm\renderer\EditorControl::class,
		'handlebars-editor' => \warm\renderer\EditorControl::class,
		'html-editor' => \warm\renderer\EditorControl::class,
		'ini-editor' => \warm\renderer\EditorControl::class,
		'java-editor' => \warm\renderer\EditorControl::class,
		'javascript-editor' => \warm\renderer\EditorControl::class,
		'json-editor' => \warm\renderer\EditorControl::class,
		'less-editor' => \warm\renderer\EditorControl::class,
		'lua-editor' => \warm\renderer\EditorControl::class,
		'markdown-editor' => \warm\renderer\EditorControl::class,
		'msdax-editor' => \warm\renderer\EditorControl::class,
		'objective-c-editor' => \warm\renderer\EditorControl::class,
		'php-editor' => \warm\renderer\EditorControl::class,
		'plaintext-editor' => \warm\renderer\EditorControl::class,
		'postiats-editor' => \warm\renderer\EditorControl::class,
		'powershell-editor' => \warm\renderer\EditorControl::class,
		'pug-editor' => \warm\renderer\EditorControl::class,
		'python-editor' => \warm\renderer\EditorControl::class,
		'r-editor' => \warm\renderer\EditorControl::class,
		'razor-editor' => \warm\renderer\EditorControl::class,
		'ruby-editor' => \warm\renderer\EditorControl::class,
		'sb-editor' => \warm\renderer\EditorControl::class,
		'scss-editor' => \warm\renderer\EditorControl::class,
		'sol-editor' => \warm\renderer\EditorControl::class,
		'sql-editor' => \warm\renderer\EditorControl::class,
		'swift-editor' => \warm\renderer\EditorControl::class,
		'typescript-editor' => \warm\renderer\EditorControl::class,
		'vb-editor' => \warm\renderer\EditorControl::class,
		'xml-editor' => \warm\renderer\EditorControl::class,
		'yaml-editor' => \warm\renderer\EditorControl::class,
		'fieldset' => \warm\renderer\FieldSetControl::class,
		'fieldSet' => \warm\renderer\FieldSetControl::class,
		'input-file' => \warm\renderer\FileControl::class,
		'formula' => \warm\renderer\FormulaControl::class,
		'grid' => \warm\renderer\Grid::class,
		'group' => \warm\renderer\GroupControl::class,
		'hbox' => \warm\renderer\HBox::class,
		'hidden' => \warm\renderer\HiddenControl::class,
		'icon-picker' => \warm\renderer\IconPickerControl::class,
		'icon-select' => \warm\renderer\Component::class,
		'input-image' => \warm\renderer\ImageControl::class,
		'input-group' => \warm\renderer\InputGroupControl::class,
		'list-select' => \warm\renderer\ListControl::class,
		'location-picker' => \warm\renderer\LocationControl::class,
		'matrix-checkboxes' => \warm\renderer\MatrixControl::class,
		'input-month-range' => \warm\renderer\MonthRangeControl::class,
		'input-quarter-range' => \warm\renderer\QuarterRangeControl::class,
		'nested-select' => \warm\renderer\NestedSelectControl::class,
		'input-number' => \warm\renderer\NumberControl::class,
		'panel' => \warm\renderer\Panel::class,
		'picker' => \warm\renderer\PickerControl::class,
		'radio' => \warm\renderer\RadioControl::class,
		'radios' => \warm\renderer\RadiosControl::class,
		'input-range' => \warm\renderer\RangeControl::class,
		'input-rating' => \warm\renderer\RatingControl::class,
		'input-repeat' => \warm\renderer\RepeatControl::class,
		'input-rich-text' => \warm\renderer\RichTextControl::class,
		'select' => \warm\renderer\SelectControl::class,
		'service' => \warm\renderer\Service::class,
		'static' => \warm\renderer\StaticExactControl::class,
		'input-sub-form' => \warm\renderer\SubFormControl::class,
		'switch' => \warm\renderer\SwitchControl::class,
		'input-table' => \warm\renderer\TableControl::class,
		'tabs' => \warm\renderer\Tabs::class,
		'tabs-transfer' => \warm\renderer\TabsTransferControl::class,
		'input-tag' => \warm\renderer\TagControl::class,
		'input-text' => \warm\renderer\TextControl::class,
		'input-password' => \warm\renderer\TextControl::class,
		'input-email' => \warm\renderer\TextControl::class,
		'input-url' => \warm\renderer\TextControl::class,
		'uuid' => \warm\renderer\UUIDControl::class,
		'multi-select' => \warm\renderer\SelectControl::class,
		'textarea' => \warm\renderer\TextareaControl::class,
		'transfer' => \warm\renderer\TransferControl::class,
		'transfer-picker' => \warm\renderer\TransferPickerControl::class,
		'tabs-transfer-picker' => \warm\renderer\TabsTransferPickerControl::class,
		'input-tree' => \warm\renderer\TreeControl::class,
		'tree-select' => \warm\renderer\TreeSelectControl::class,
		'table-view' => \warm\renderer\TableView::class,
		'portlet' => \warm\renderer\Portlet::class,
		'grid-nav' => \warm\renderer\GridNav::class,
		'users-select' => \warm\renderer\UserSelectControl::class,
		'tag' => \warm\renderer\Tag::class,
		'tags' => \warm\renderer\Component::class,
		'words' => \warm\renderer\Words::class,
		'password' => \warm\renderer\Password::class,
		'multiline-text' => \warm\renderer\MultilineText::class,
		'amis' => \warm\renderer\Component::class,
		'native-date' => \warm\renderer\TextControl::class,
		'native-time' => \warm\renderer\TextControl::class,
		'native-number' => \warm\renderer\TextControl::class,
		'code' => \warm\renderer\Code::class,
		'tooltip-wrapper' => \warm\renderer\TooltipWrapper::class,
	]));
	override(\warm\renderer\TableColumn::type(0), map([
		'form' => \warm\renderer\Form::class,
		'alert' => \warm\renderer\Alert::class,
		'app' => \warm\renderer\Component::class,
		'audio' => \warm\renderer\Audio::class,
		'avatar' => \warm\renderer\Avatar::class,
		'button-group' => \warm\renderer\ButtonGroup::class,
		'breadcrumb' => \warm\renderer\Breadcrumb::class,
		'card' => \warm\renderer\Card::class,
		'card2' => \warm\renderer\Card2::class,
		'cards' => \warm\renderer\Cards::class,
		'carousel' => \warm\renderer\Carousel::class,
		'chart' => \warm\renderer\Chart::class,
		'calendar' => \warm\renderer\Calendar::class,
		'collapse' => \warm\renderer\Collapse::class,
		'collapse-group' => \warm\renderer\CollapseGroup::class,
		'color' => \warm\renderer\Color::class,
		'crud' => \warm\renderer\CRUDTable::class,
		'crud2' => \warm\renderer\CRUD2Table::class,
		'custom' => \warm\renderer\Custom::class,
		'date' => \warm\renderer\Date::class,
		'static-date' => \warm\renderer\StaticExactControl::class,
		'datetime' => \warm\renderer\Date::class,
		'static-datetime' => \warm\renderer\StaticExactControl::class,
		'time' => \warm\renderer\Date::class,
		'static-time' => \warm\renderer\StaticExactControl::class,
		'month' => \warm\renderer\Date::class,
		'static-month' => \warm\renderer\StaticExactControl::class,
		'date-range' => \warm\renderer\DateRange::class,
		'dialog' => \warm\renderer\Dialog::class,
		'spinner' => \warm\renderer\Spinner::class,
		'divider' => \warm\renderer\Divider::class,
		'dropdown-button' => \warm\renderer\DropdownButton::class,
		'drawer' => \warm\renderer\Drawer::class,
		'each' => \warm\renderer\Each::class,
		'flex' => \warm\renderer\Flex::class,
		'flex-item' => \warm\renderer\Component::class,
		'grid-2d' => \warm\renderer\Grid2D::class,
		'icon' => \warm\renderer\Icon::class,
		'iframe' => \warm\renderer\IFrame::class,
		'image' => \warm\renderer\Image::class,
		'static-image' => \warm\renderer\StaticExactControl::class,
		'images' => \warm\renderer\Images::class,
		'static-images' => \warm\renderer\Component::class,
		'json-schema' => \warm\renderer\Json::class,
		'json-schema-editor' => \warm\renderer\JSONSchemaEditorControl::class,
		'json' => \warm\renderer\Json::class,
		'static-json' => \warm\renderer\Component::class,
		'link' => \warm\renderer\Link::class,
		'list' => \warm\renderer\ListRenderer::class,
		'log' => \warm\renderer\Log::class,
		'static-list' => \warm\renderer\Component::class,
		'map' => \warm\renderer\Mapping::class,
		'mapping' => \warm\renderer\Mapping::class,
		'markdown' => \warm\renderer\Markdown::class,
		'nav' => \warm\renderer\Nav::class,
		'number' => \warm\renderer\Component::class,
		'page' => \warm\renderer\Page::class,
		'pagination' => \warm\renderer\Pagination::class,
		'pagination-wrapper' => \warm\renderer\PaginationWrapper::class,
		'property' => \warm\renderer\Property::class,
		'operation' => \warm\renderer\Operation::class,
		'plain' => \warm\renderer\Plain::class,
		'text' => \warm\renderer\Component::class,
		'progress' => \warm\renderer\Progress::class,
		'qrcode' => \warm\renderer\QRCode::class,
		'qr-code' => \warm\renderer\QRCode::class,
		'barcode' => \warm\renderer\Barcode::class,
		'remark' => \warm\renderer\Remark::class,
		'search-box' => \warm\renderer\SearchBox::class,
		'sparkline' => \warm\renderer\SparkLine::class,
		'status' => \warm\renderer\Status::class,
		'table' => \warm\renderer\Table::class,
		'static-table' => \warm\renderer\StaticExactControl::class,
		'table2' => \warm\renderer\TableSchema2::class,
		'html' => \warm\renderer\Html::class,
		'tpl' => \warm\renderer\Tpl::class,
		'tasks' => \warm\renderer\Tasks::class,
		'vbox' => \warm\renderer\VBox::class,
		'video' => \warm\renderer\Video::class,
		'wizard' => \warm\renderer\Wizard::class,
		'wrapper' => \warm\renderer\Wrapper::class,
		'web-component' => \warm\renderer\WebComponent::class,
		'anchor-nav' => \warm\renderer\AnchorNav::class,
		'steps' => \warm\renderer\Steps::class,
		'timeline' => \warm\renderer\Timeline::class,
		'control' => \warm\renderer\FormControl::class,
		'input-array' => \warm\renderer\ArrayControl::class,
		'button' => \warm\renderer\VanillaAction::class,
		'submit' => \warm\renderer\VanillaAction::class,
		'reset' => \warm\renderer\VanillaAction::class,
		'button-group-select' => \warm\renderer\ButtonGroupControl::class,
		'button-toolbar' => \warm\renderer\ButtonToolbar::class,
		'chained-select' => \warm\renderer\ChainedSelectControl::class,
		'chart-radios' => \warm\renderer\ChartRadios::class,
		'checkbox' => \warm\renderer\CheckboxControl::class,
		'checkboxes' => \warm\renderer\CheckboxesControl::class,
		'input-city' => \warm\renderer\InputCityControl::class,
		'input-color' => \warm\renderer\InputColorControl::class,
		'combo' => \warm\renderer\ComboControl::class,
		'condition-builder' => \warm\renderer\ConditionBuilderControl::class,
		'container' => \warm\renderer\Container::class,
		'switch-container' => \warm\renderer\SwitchContainer::class,
		'input-date' => \warm\renderer\DateControl::class,
		'input-datetime' => \warm\renderer\DateTimeControl::class,
		'input-time' => \warm\renderer\TimeControl::class,
		'input-quarter' => \warm\renderer\QuarterControl::class,
		'input-year' => \warm\renderer\YearControl::class,
		'input-month' => \warm\renderer\MonthControl::class,
		'input-date-range' => \warm\renderer\DateRangeControl::class,
		'input-time-range' => \warm\renderer\DateRangeControl::class,
		'input-datetime-range' => \warm\renderer\DateRangeControl::class,
		'input-excel' => \warm\renderer\InputExcel::class,
		'input-formula' => \warm\renderer\Component::class,
		'diff-editor' => \warm\renderer\DiffControl::class,
		'office-viewer' => \warm\renderer\Component::class,
		'pdf-viewer' => \warm\renderer\Component::class,
		'input-signature' => \warm\renderer\InputSignature::class,
		'editor' => \warm\renderer\EditorControl::class,
		'bat-editor' => \warm\renderer\EditorControl::class,
		'c-editor' => \warm\renderer\EditorControl::class,
		'coffeescript-editor' => \warm\renderer\EditorControl::class,
		'cpp-editor' => \warm\renderer\EditorControl::class,
		'csharp-editor' => \warm\renderer\EditorControl::class,
		'css-editor' => \warm\renderer\EditorControl::class,
		'dockerfile-editor' => \warm\renderer\EditorControl::class,
		'fsharp-editor' => \warm\renderer\EditorControl::class,
		'go-editor' => \warm\renderer\EditorControl::class,
		'handlebars-editor' => \warm\renderer\EditorControl::class,
		'html-editor' => \warm\renderer\EditorControl::class,
		'ini-editor' => \warm\renderer\EditorControl::class,
		'java-editor' => \warm\renderer\EditorControl::class,
		'javascript-editor' => \warm\renderer\EditorControl::class,
		'json-editor' => \warm\renderer\EditorControl::class,
		'less-editor' => \warm\renderer\EditorControl::class,
		'lua-editor' => \warm\renderer\EditorControl::class,
		'markdown-editor' => \warm\renderer\EditorControl::class,
		'msdax-editor' => \warm\renderer\EditorControl::class,
		'objective-c-editor' => \warm\renderer\EditorControl::class,
		'php-editor' => \warm\renderer\EditorControl::class,
		'plaintext-editor' => \warm\renderer\EditorControl::class,
		'postiats-editor' => \warm\renderer\EditorControl::class,
		'powershell-editor' => \warm\renderer\EditorControl::class,
		'pug-editor' => \warm\renderer\EditorControl::class,
		'python-editor' => \warm\renderer\EditorControl::class,
		'r-editor' => \warm\renderer\EditorControl::class,
		'razor-editor' => \warm\renderer\EditorControl::class,
		'ruby-editor' => \warm\renderer\EditorControl::class,
		'sb-editor' => \warm\renderer\EditorControl::class,
		'scss-editor' => \warm\renderer\EditorControl::class,
		'sol-editor' => \warm\renderer\EditorControl::class,
		'sql-editor' => \warm\renderer\EditorControl::class,
		'swift-editor' => \warm\renderer\EditorControl::class,
		'typescript-editor' => \warm\renderer\EditorControl::class,
		'vb-editor' => \warm\renderer\EditorControl::class,
		'xml-editor' => \warm\renderer\EditorControl::class,
		'yaml-editor' => \warm\renderer\EditorControl::class,
		'fieldset' => \warm\renderer\FieldSetControl::class,
		'fieldSet' => \warm\renderer\FieldSetControl::class,
		'input-file' => \warm\renderer\FileControl::class,
		'formula' => \warm\renderer\FormulaControl::class,
		'grid' => \warm\renderer\Grid::class,
		'group' => \warm\renderer\GroupControl::class,
		'hbox' => \warm\renderer\HBox::class,
		'hidden' => \warm\renderer\HiddenControl::class,
		'icon-picker' => \warm\renderer\IconPickerControl::class,
		'icon-select' => \warm\renderer\Component::class,
		'input-image' => \warm\renderer\ImageControl::class,
		'input-group' => \warm\renderer\InputGroupControl::class,
		'list-select' => \warm\renderer\ListControl::class,
		'location-picker' => \warm\renderer\LocationControl::class,
		'matrix-checkboxes' => \warm\renderer\MatrixControl::class,
		'input-month-range' => \warm\renderer\MonthRangeControl::class,
		'input-quarter-range' => \warm\renderer\QuarterRangeControl::class,
		'nested-select' => \warm\renderer\NestedSelectControl::class,
		'input-number' => \warm\renderer\NumberControl::class,
		'panel' => \warm\renderer\Panel::class,
		'picker' => \warm\renderer\PickerControl::class,
		'radio' => \warm\renderer\RadioControl::class,
		'radios' => \warm\renderer\RadiosControl::class,
		'input-range' => \warm\renderer\RangeControl::class,
		'input-rating' => \warm\renderer\RatingControl::class,
		'input-repeat' => \warm\renderer\RepeatControl::class,
		'input-rich-text' => \warm\renderer\RichTextControl::class,
		'select' => \warm\renderer\SelectControl::class,
		'service' => \warm\renderer\Service::class,
		'static' => \warm\renderer\StaticExactControl::class,
		'input-sub-form' => \warm\renderer\SubFormControl::class,
		'switch' => \warm\renderer\SwitchControl::class,
		'input-table' => \warm\renderer\TableControl::class,
		'tabs' => \warm\renderer\Tabs::class,
		'tabs-transfer' => \warm\renderer\TabsTransferControl::class,
		'input-tag' => \warm\renderer\TagControl::class,
		'input-text' => \warm\renderer\TextControl::class,
		'input-password' => \warm\renderer\TextControl::class,
		'input-email' => \warm\renderer\TextControl::class,
		'input-url' => \warm\renderer\TextControl::class,
		'uuid' => \warm\renderer\UUIDControl::class,
		'multi-select' => \warm\renderer\SelectControl::class,
		'textarea' => \warm\renderer\TextareaControl::class,
		'transfer' => \warm\renderer\TransferControl::class,
		'transfer-picker' => \warm\renderer\TransferPickerControl::class,
		'tabs-transfer-picker' => \warm\renderer\TabsTransferPickerControl::class,
		'input-tree' => \warm\renderer\TreeControl::class,
		'tree-select' => \warm\renderer\TreeSelectControl::class,
		'table-view' => \warm\renderer\TableView::class,
		'portlet' => \warm\renderer\Portlet::class,
		'grid-nav' => \warm\renderer\GridNav::class,
		'users-select' => \warm\renderer\UserSelectControl::class,
		'tag' => \warm\renderer\Tag::class,
		'tags' => \warm\renderer\Component::class,
		'words' => \warm\renderer\Words::class,
		'password' => \warm\renderer\Password::class,
		'multiline-text' => \warm\renderer\MultilineText::class,
		'amis' => \warm\renderer\Component::class,
		'native-date' => \warm\renderer\TextControl::class,
		'native-time' => \warm\renderer\TextControl::class,
		'native-number' => \warm\renderer\TextControl::class,
		'code' => \warm\renderer\Code::class,
		'tooltip-wrapper' => \warm\renderer\TooltipWrapper::class,
	]));
	override(\warm\renderer\StaticExactControl::type(0), map([
		'form' => \warm\renderer\Form::class,
		'alert' => \warm\renderer\Alert::class,
		'app' => \warm\renderer\Component::class,
		'audio' => \warm\renderer\Audio::class,
		'avatar' => \warm\renderer\Avatar::class,
		'button-group' => \warm\renderer\ButtonGroup::class,
		'breadcrumb' => \warm\renderer\Breadcrumb::class,
		'card' => \warm\renderer\Card::class,
		'card2' => \warm\renderer\Card2::class,
		'cards' => \warm\renderer\Cards::class,
		'carousel' => \warm\renderer\Carousel::class,
		'chart' => \warm\renderer\Chart::class,
		'calendar' => \warm\renderer\Calendar::class,
		'collapse' => \warm\renderer\Collapse::class,
		'collapse-group' => \warm\renderer\CollapseGroup::class,
		'color' => \warm\renderer\Color::class,
		'crud' => \warm\renderer\CRUDTable::class,
		'crud2' => \warm\renderer\CRUD2Table::class,
		'custom' => \warm\renderer\Custom::class,
		'date' => \warm\renderer\Date::class,
		'static-date' => \warm\renderer\StaticExactControl::class,
		'datetime' => \warm\renderer\Date::class,
		'static-datetime' => \warm\renderer\StaticExactControl::class,
		'time' => \warm\renderer\Date::class,
		'static-time' => \warm\renderer\StaticExactControl::class,
		'month' => \warm\renderer\Date::class,
		'static-month' => \warm\renderer\StaticExactControl::class,
		'date-range' => \warm\renderer\DateRange::class,
		'dialog' => \warm\renderer\Dialog::class,
		'spinner' => \warm\renderer\Spinner::class,
		'divider' => \warm\renderer\Divider::class,
		'dropdown-button' => \warm\renderer\DropdownButton::class,
		'drawer' => \warm\renderer\Drawer::class,
		'each' => \warm\renderer\Each::class,
		'flex' => \warm\renderer\Flex::class,
		'flex-item' => \warm\renderer\Component::class,
		'grid-2d' => \warm\renderer\Grid2D::class,
		'icon' => \warm\renderer\Icon::class,
		'iframe' => \warm\renderer\IFrame::class,
		'image' => \warm\renderer\Image::class,
		'static-image' => \warm\renderer\StaticExactControl::class,
		'images' => \warm\renderer\Images::class,
		'static-images' => \warm\renderer\Component::class,
		'json-schema' => \warm\renderer\Json::class,
		'json-schema-editor' => \warm\renderer\JSONSchemaEditorControl::class,
		'json' => \warm\renderer\Json::class,
		'static-json' => \warm\renderer\Component::class,
		'link' => \warm\renderer\Link::class,
		'list' => \warm\renderer\ListRenderer::class,
		'log' => \warm\renderer\Log::class,
		'static-list' => \warm\renderer\Component::class,
		'map' => \warm\renderer\Mapping::class,
		'mapping' => \warm\renderer\Mapping::class,
		'markdown' => \warm\renderer\Markdown::class,
		'nav' => \warm\renderer\Nav::class,
		'number' => \warm\renderer\Component::class,
		'page' => \warm\renderer\Page::class,
		'pagination' => \warm\renderer\Pagination::class,
		'pagination-wrapper' => \warm\renderer\PaginationWrapper::class,
		'property' => \warm\renderer\Property::class,
		'operation' => \warm\renderer\Operation::class,
		'plain' => \warm\renderer\Plain::class,
		'text' => \warm\renderer\Component::class,
		'progress' => \warm\renderer\Progress::class,
		'qrcode' => \warm\renderer\QRCode::class,
		'qr-code' => \warm\renderer\QRCode::class,
		'barcode' => \warm\renderer\Barcode::class,
		'remark' => \warm\renderer\Remark::class,
		'search-box' => \warm\renderer\SearchBox::class,
		'sparkline' => \warm\renderer\SparkLine::class,
		'status' => \warm\renderer\Status::class,
		'table' => \warm\renderer\Table::class,
		'static-table' => \warm\renderer\StaticExactControl::class,
		'table2' => \warm\renderer\TableSchema2::class,
		'html' => \warm\renderer\Html::class,
		'tpl' => \warm\renderer\Tpl::class,
		'tasks' => \warm\renderer\Tasks::class,
		'vbox' => \warm\renderer\VBox::class,
		'video' => \warm\renderer\Video::class,
		'wizard' => \warm\renderer\Wizard::class,
		'wrapper' => \warm\renderer\Wrapper::class,
		'web-component' => \warm\renderer\WebComponent::class,
		'anchor-nav' => \warm\renderer\AnchorNav::class,
		'steps' => \warm\renderer\Steps::class,
		'timeline' => \warm\renderer\Timeline::class,
		'control' => \warm\renderer\FormControl::class,
		'input-array' => \warm\renderer\ArrayControl::class,
		'button' => \warm\renderer\VanillaAction::class,
		'submit' => \warm\renderer\VanillaAction::class,
		'reset' => \warm\renderer\VanillaAction::class,
		'button-group-select' => \warm\renderer\ButtonGroupControl::class,
		'button-toolbar' => \warm\renderer\ButtonToolbar::class,
		'chained-select' => \warm\renderer\ChainedSelectControl::class,
		'chart-radios' => \warm\renderer\ChartRadios::class,
		'checkbox' => \warm\renderer\CheckboxControl::class,
		'checkboxes' => \warm\renderer\CheckboxesControl::class,
		'input-city' => \warm\renderer\InputCityControl::class,
		'input-color' => \warm\renderer\InputColorControl::class,
		'combo' => \warm\renderer\ComboControl::class,
		'condition-builder' => \warm\renderer\ConditionBuilderControl::class,
		'container' => \warm\renderer\Container::class,
		'switch-container' => \warm\renderer\SwitchContainer::class,
		'input-date' => \warm\renderer\DateControl::class,
		'input-datetime' => \warm\renderer\DateTimeControl::class,
		'input-time' => \warm\renderer\TimeControl::class,
		'input-quarter' => \warm\renderer\QuarterControl::class,
		'input-year' => \warm\renderer\YearControl::class,
		'input-month' => \warm\renderer\MonthControl::class,
		'input-date-range' => \warm\renderer\DateRangeControl::class,
		'input-time-range' => \warm\renderer\DateRangeControl::class,
		'input-datetime-range' => \warm\renderer\DateRangeControl::class,
		'input-excel' => \warm\renderer\InputExcel::class,
		'input-formula' => \warm\renderer\Component::class,
		'diff-editor' => \warm\renderer\DiffControl::class,
		'office-viewer' => \warm\renderer\Component::class,
		'pdf-viewer' => \warm\renderer\Component::class,
		'input-signature' => \warm\renderer\InputSignature::class,
		'editor' => \warm\renderer\EditorControl::class,
		'bat-editor' => \warm\renderer\EditorControl::class,
		'c-editor' => \warm\renderer\EditorControl::class,
		'coffeescript-editor' => \warm\renderer\EditorControl::class,
		'cpp-editor' => \warm\renderer\EditorControl::class,
		'csharp-editor' => \warm\renderer\EditorControl::class,
		'css-editor' => \warm\renderer\EditorControl::class,
		'dockerfile-editor' => \warm\renderer\EditorControl::class,
		'fsharp-editor' => \warm\renderer\EditorControl::class,
		'go-editor' => \warm\renderer\EditorControl::class,
		'handlebars-editor' => \warm\renderer\EditorControl::class,
		'html-editor' => \warm\renderer\EditorControl::class,
		'ini-editor' => \warm\renderer\EditorControl::class,
		'java-editor' => \warm\renderer\EditorControl::class,
		'javascript-editor' => \warm\renderer\EditorControl::class,
		'json-editor' => \warm\renderer\EditorControl::class,
		'less-editor' => \warm\renderer\EditorControl::class,
		'lua-editor' => \warm\renderer\EditorControl::class,
		'markdown-editor' => \warm\renderer\EditorControl::class,
		'msdax-editor' => \warm\renderer\EditorControl::class,
		'objective-c-editor' => \warm\renderer\EditorControl::class,
		'php-editor' => \warm\renderer\EditorControl::class,
		'plaintext-editor' => \warm\renderer\EditorControl::class,
		'postiats-editor' => \warm\renderer\EditorControl::class,
		'powershell-editor' => \warm\renderer\EditorControl::class,
		'pug-editor' => \warm\renderer\EditorControl::class,
		'python-editor' => \warm\renderer\EditorControl::class,
		'r-editor' => \warm\renderer\EditorControl::class,
		'razor-editor' => \warm\renderer\EditorControl::class,
		'ruby-editor' => \warm\renderer\EditorControl::class,
		'sb-editor' => \warm\renderer\EditorControl::class,
		'scss-editor' => \warm\renderer\EditorControl::class,
		'sol-editor' => \warm\renderer\EditorControl::class,
		'sql-editor' => \warm\renderer\EditorControl::class,
		'swift-editor' => \warm\renderer\EditorControl::class,
		'typescript-editor' => \warm\renderer\EditorControl::class,
		'vb-editor' => \warm\renderer\EditorControl::class,
		'xml-editor' => \warm\renderer\EditorControl::class,
		'yaml-editor' => \warm\renderer\EditorControl::class,
		'fieldset' => \warm\renderer\FieldSetControl::class,
		'fieldSet' => \warm\renderer\FieldSetControl::class,
		'input-file' => \warm\renderer\FileControl::class,
		'formula' => \warm\renderer\FormulaControl::class,
		'grid' => \warm\renderer\Grid::class,
		'group' => \warm\renderer\GroupControl::class,
		'hbox' => \warm\renderer\HBox::class,
		'hidden' => \warm\renderer\HiddenControl::class,
		'icon-picker' => \warm\renderer\IconPickerControl::class,
		'icon-select' => \warm\renderer\Component::class,
		'input-image' => \warm\renderer\ImageControl::class,
		'input-group' => \warm\renderer\InputGroupControl::class,
		'list-select' => \warm\renderer\ListControl::class,
		'location-picker' => \warm\renderer\LocationControl::class,
		'matrix-checkboxes' => \warm\renderer\MatrixControl::class,
		'input-month-range' => \warm\renderer\MonthRangeControl::class,
		'input-quarter-range' => \warm\renderer\QuarterRangeControl::class,
		'nested-select' => \warm\renderer\NestedSelectControl::class,
		'input-number' => \warm\renderer\NumberControl::class,
		'panel' => \warm\renderer\Panel::class,
		'picker' => \warm\renderer\PickerControl::class,
		'radio' => \warm\renderer\RadioControl::class,
		'radios' => \warm\renderer\RadiosControl::class,
		'input-range' => \warm\renderer\RangeControl::class,
		'input-rating' => \warm\renderer\RatingControl::class,
		'input-repeat' => \warm\renderer\RepeatControl::class,
		'input-rich-text' => \warm\renderer\RichTextControl::class,
		'select' => \warm\renderer\SelectControl::class,
		'service' => \warm\renderer\Service::class,
		'static' => \warm\renderer\StaticExactControl::class,
		'input-sub-form' => \warm\renderer\SubFormControl::class,
		'switch' => \warm\renderer\SwitchControl::class,
		'input-table' => \warm\renderer\TableControl::class,
		'tabs' => \warm\renderer\Tabs::class,
		'tabs-transfer' => \warm\renderer\TabsTransferControl::class,
		'input-tag' => \warm\renderer\TagControl::class,
		'input-text' => \warm\renderer\TextControl::class,
		'input-password' => \warm\renderer\TextControl::class,
		'input-email' => \warm\renderer\TextControl::class,
		'input-url' => \warm\renderer\TextControl::class,
		'uuid' => \warm\renderer\UUIDControl::class,
		'multi-select' => \warm\renderer\SelectControl::class,
		'textarea' => \warm\renderer\TextareaControl::class,
		'transfer' => \warm\renderer\TransferControl::class,
		'transfer-picker' => \warm\renderer\TransferPickerControl::class,
		'tabs-transfer-picker' => \warm\renderer\TabsTransferPickerControl::class,
		'input-tree' => \warm\renderer\TreeControl::class,
		'tree-select' => \warm\renderer\TreeSelectControl::class,
		'table-view' => \warm\renderer\TableView::class,
		'portlet' => \warm\renderer\Portlet::class,
		'grid-nav' => \warm\renderer\GridNav::class,
		'users-select' => \warm\renderer\UserSelectControl::class,
		'tag' => \warm\renderer\Tag::class,
		'tags' => \warm\renderer\Component::class,
		'words' => \warm\renderer\Words::class,
		'password' => \warm\renderer\Password::class,
		'multiline-text' => \warm\renderer\MultilineText::class,
		'amis' => \warm\renderer\Component::class,
		'native-date' => \warm\renderer\TextControl::class,
		'native-time' => \warm\renderer\TextControl::class,
		'native-number' => \warm\renderer\TextControl::class,
		'code' => \warm\renderer\Code::class,
		'tooltip-wrapper' => \warm\renderer\TooltipWrapper::class,
	]));
	override(\warm\renderer\Column::type(0), map([
		'form' => \warm\renderer\Form::class,
		'alert' => \warm\renderer\Alert::class,
		'app' => \warm\renderer\Component::class,
		'audio' => \warm\renderer\Audio::class,
		'avatar' => \warm\renderer\Avatar::class,
		'button-group' => \warm\renderer\ButtonGroup::class,
		'breadcrumb' => \warm\renderer\Breadcrumb::class,
		'card' => \warm\renderer\Card::class,
		'card2' => \warm\renderer\Card2::class,
		'cards' => \warm\renderer\Cards::class,
		'carousel' => \warm\renderer\Carousel::class,
		'chart' => \warm\renderer\Chart::class,
		'calendar' => \warm\renderer\Calendar::class,
		'collapse' => \warm\renderer\Collapse::class,
		'collapse-group' => \warm\renderer\CollapseGroup::class,
		'color' => \warm\renderer\Color::class,
		'crud' => \warm\renderer\CRUDTable::class,
		'crud2' => \warm\renderer\CRUD2Table::class,
		'custom' => \warm\renderer\Custom::class,
		'date' => \warm\renderer\Date::class,
		'static-date' => \warm\renderer\StaticExactControl::class,
		'datetime' => \warm\renderer\Date::class,
		'static-datetime' => \warm\renderer\StaticExactControl::class,
		'time' => \warm\renderer\Date::class,
		'static-time' => \warm\renderer\StaticExactControl::class,
		'month' => \warm\renderer\Date::class,
		'static-month' => \warm\renderer\StaticExactControl::class,
		'date-range' => \warm\renderer\DateRange::class,
		'dialog' => \warm\renderer\Dialog::class,
		'spinner' => \warm\renderer\Spinner::class,
		'divider' => \warm\renderer\Divider::class,
		'dropdown-button' => \warm\renderer\DropdownButton::class,
		'drawer' => \warm\renderer\Drawer::class,
		'each' => \warm\renderer\Each::class,
		'flex' => \warm\renderer\Flex::class,
		'flex-item' => \warm\renderer\Component::class,
		'grid-2d' => \warm\renderer\Grid2D::class,
		'icon' => \warm\renderer\Icon::class,
		'iframe' => \warm\renderer\IFrame::class,
		'image' => \warm\renderer\Image::class,
		'static-image' => \warm\renderer\StaticExactControl::class,
		'images' => \warm\renderer\Images::class,
		'static-images' => \warm\renderer\Component::class,
		'json-schema' => \warm\renderer\Json::class,
		'json-schema-editor' => \warm\renderer\JSONSchemaEditorControl::class,
		'json' => \warm\renderer\Json::class,
		'static-json' => \warm\renderer\Component::class,
		'link' => \warm\renderer\Link::class,
		'list' => \warm\renderer\ListRenderer::class,
		'log' => \warm\renderer\Log::class,
		'static-list' => \warm\renderer\Component::class,
		'map' => \warm\renderer\Mapping::class,
		'mapping' => \warm\renderer\Mapping::class,
		'markdown' => \warm\renderer\Markdown::class,
		'nav' => \warm\renderer\Nav::class,
		'number' => \warm\renderer\Component::class,
		'page' => \warm\renderer\Page::class,
		'pagination' => \warm\renderer\Pagination::class,
		'pagination-wrapper' => \warm\renderer\PaginationWrapper::class,
		'property' => \warm\renderer\Property::class,
		'operation' => \warm\renderer\Operation::class,
		'plain' => \warm\renderer\Plain::class,
		'text' => \warm\renderer\Component::class,
		'progress' => \warm\renderer\Progress::class,
		'qrcode' => \warm\renderer\QRCode::class,
		'qr-code' => \warm\renderer\QRCode::class,
		'barcode' => \warm\renderer\Barcode::class,
		'remark' => \warm\renderer\Remark::class,
		'search-box' => \warm\renderer\SearchBox::class,
		'sparkline' => \warm\renderer\SparkLine::class,
		'status' => \warm\renderer\Status::class,
		'table' => \warm\renderer\Table::class,
		'static-table' => \warm\renderer\StaticExactControl::class,
		'table2' => \warm\renderer\TableSchema2::class,
		'html' => \warm\renderer\Html::class,
		'tpl' => \warm\renderer\Tpl::class,
		'tasks' => \warm\renderer\Tasks::class,
		'vbox' => \warm\renderer\VBox::class,
		'video' => \warm\renderer\Video::class,
		'wizard' => \warm\renderer\Wizard::class,
		'wrapper' => \warm\renderer\Wrapper::class,
		'web-component' => \warm\renderer\WebComponent::class,
		'anchor-nav' => \warm\renderer\AnchorNav::class,
		'steps' => \warm\renderer\Steps::class,
		'timeline' => \warm\renderer\Timeline::class,
		'control' => \warm\renderer\FormControl::class,
		'input-array' => \warm\renderer\ArrayControl::class,
		'button' => \warm\renderer\VanillaAction::class,
		'submit' => \warm\renderer\VanillaAction::class,
		'reset' => \warm\renderer\VanillaAction::class,
		'button-group-select' => \warm\renderer\ButtonGroupControl::class,
		'button-toolbar' => \warm\renderer\ButtonToolbar::class,
		'chained-select' => \warm\renderer\ChainedSelectControl::class,
		'chart-radios' => \warm\renderer\ChartRadios::class,
		'checkbox' => \warm\renderer\CheckboxControl::class,
		'checkboxes' => \warm\renderer\CheckboxesControl::class,
		'input-city' => \warm\renderer\InputCityControl::class,
		'input-color' => \warm\renderer\InputColorControl::class,
		'combo' => \warm\renderer\ComboControl::class,
		'condition-builder' => \warm\renderer\ConditionBuilderControl::class,
		'container' => \warm\renderer\Container::class,
		'switch-container' => \warm\renderer\SwitchContainer::class,
		'input-date' => \warm\renderer\DateControl::class,
		'input-datetime' => \warm\renderer\DateTimeControl::class,
		'input-time' => \warm\renderer\TimeControl::class,
		'input-quarter' => \warm\renderer\QuarterControl::class,
		'input-year' => \warm\renderer\YearControl::class,
		'input-month' => \warm\renderer\MonthControl::class,
		'input-date-range' => \warm\renderer\DateRangeControl::class,
		'input-time-range' => \warm\renderer\DateRangeControl::class,
		'input-datetime-range' => \warm\renderer\DateRangeControl::class,
		'input-excel' => \warm\renderer\InputExcel::class,
		'input-formula' => \warm\renderer\Component::class,
		'diff-editor' => \warm\renderer\DiffControl::class,
		'office-viewer' => \warm\renderer\Component::class,
		'pdf-viewer' => \warm\renderer\Component::class,
		'input-signature' => \warm\renderer\InputSignature::class,
		'editor' => \warm\renderer\EditorControl::class,
		'bat-editor' => \warm\renderer\EditorControl::class,
		'c-editor' => \warm\renderer\EditorControl::class,
		'coffeescript-editor' => \warm\renderer\EditorControl::class,
		'cpp-editor' => \warm\renderer\EditorControl::class,
		'csharp-editor' => \warm\renderer\EditorControl::class,
		'css-editor' => \warm\renderer\EditorControl::class,
		'dockerfile-editor' => \warm\renderer\EditorControl::class,
		'fsharp-editor' => \warm\renderer\EditorControl::class,
		'go-editor' => \warm\renderer\EditorControl::class,
		'handlebars-editor' => \warm\renderer\EditorControl::class,
		'html-editor' => \warm\renderer\EditorControl::class,
		'ini-editor' => \warm\renderer\EditorControl::class,
		'java-editor' => \warm\renderer\EditorControl::class,
		'javascript-editor' => \warm\renderer\EditorControl::class,
		'json-editor' => \warm\renderer\EditorControl::class,
		'less-editor' => \warm\renderer\EditorControl::class,
		'lua-editor' => \warm\renderer\EditorControl::class,
		'markdown-editor' => \warm\renderer\EditorControl::class,
		'msdax-editor' => \warm\renderer\EditorControl::class,
		'objective-c-editor' => \warm\renderer\EditorControl::class,
		'php-editor' => \warm\renderer\EditorControl::class,
		'plaintext-editor' => \warm\renderer\EditorControl::class,
		'postiats-editor' => \warm\renderer\EditorControl::class,
		'powershell-editor' => \warm\renderer\EditorControl::class,
		'pug-editor' => \warm\renderer\EditorControl::class,
		'python-editor' => \warm\renderer\EditorControl::class,
		'r-editor' => \warm\renderer\EditorControl::class,
		'razor-editor' => \warm\renderer\EditorControl::class,
		'ruby-editor' => \warm\renderer\EditorControl::class,
		'sb-editor' => \warm\renderer\EditorControl::class,
		'scss-editor' => \warm\renderer\EditorControl::class,
		'sol-editor' => \warm\renderer\EditorControl::class,
		'sql-editor' => \warm\renderer\EditorControl::class,
		'swift-editor' => \warm\renderer\EditorControl::class,
		'typescript-editor' => \warm\renderer\EditorControl::class,
		'vb-editor' => \warm\renderer\EditorControl::class,
		'xml-editor' => \warm\renderer\EditorControl::class,
		'yaml-editor' => \warm\renderer\EditorControl::class,
		'fieldset' => \warm\renderer\FieldSetControl::class,
		'fieldSet' => \warm\renderer\FieldSetControl::class,
		'input-file' => \warm\renderer\FileControl::class,
		'formula' => \warm\renderer\FormulaControl::class,
		'grid' => \warm\renderer\Grid::class,
		'group' => \warm\renderer\GroupControl::class,
		'hbox' => \warm\renderer\HBox::class,
		'hidden' => \warm\renderer\HiddenControl::class,
		'icon-picker' => \warm\renderer\IconPickerControl::class,
		'icon-select' => \warm\renderer\Component::class,
		'input-image' => \warm\renderer\ImageControl::class,
		'input-group' => \warm\renderer\InputGroupControl::class,
		'list-select' => \warm\renderer\ListControl::class,
		'location-picker' => \warm\renderer\LocationControl::class,
		'matrix-checkboxes' => \warm\renderer\MatrixControl::class,
		'input-month-range' => \warm\renderer\MonthRangeControl::class,
		'input-quarter-range' => \warm\renderer\QuarterRangeControl::class,
		'nested-select' => \warm\renderer\NestedSelectControl::class,
		'input-number' => \warm\renderer\NumberControl::class,
		'panel' => \warm\renderer\Panel::class,
		'picker' => \warm\renderer\PickerControl::class,
		'radio' => \warm\renderer\RadioControl::class,
		'radios' => \warm\renderer\RadiosControl::class,
		'input-range' => \warm\renderer\RangeControl::class,
		'input-rating' => \warm\renderer\RatingControl::class,
		'input-repeat' => \warm\renderer\RepeatControl::class,
		'input-rich-text' => \warm\renderer\RichTextControl::class,
		'select' => \warm\renderer\SelectControl::class,
		'service' => \warm\renderer\Service::class,
		'static' => \warm\renderer\StaticExactControl::class,
		'input-sub-form' => \warm\renderer\SubFormControl::class,
		'switch' => \warm\renderer\SwitchControl::class,
		'input-table' => \warm\renderer\TableControl::class,
		'tabs' => \warm\renderer\Tabs::class,
		'tabs-transfer' => \warm\renderer\TabsTransferControl::class,
		'input-tag' => \warm\renderer\TagControl::class,
		'input-text' => \warm\renderer\TextControl::class,
		'input-password' => \warm\renderer\TextControl::class,
		'input-email' => \warm\renderer\TextControl::class,
		'input-url' => \warm\renderer\TextControl::class,
		'uuid' => \warm\renderer\UUIDControl::class,
		'multi-select' => \warm\renderer\SelectControl::class,
		'textarea' => \warm\renderer\TextareaControl::class,
		'transfer' => \warm\renderer\TransferControl::class,
		'transfer-picker' => \warm\renderer\TransferPickerControl::class,
		'tabs-transfer-picker' => \warm\renderer\TabsTransferPickerControl::class,
		'input-tree' => \warm\renderer\TreeControl::class,
		'tree-select' => \warm\renderer\TreeSelectControl::class,
		'table-view' => \warm\renderer\TableView::class,
		'portlet' => \warm\renderer\Portlet::class,
		'grid-nav' => \warm\renderer\GridNav::class,
		'users-select' => \warm\renderer\UserSelectControl::class,
		'tag' => \warm\renderer\Tag::class,
		'tags' => \warm\renderer\Component::class,
		'words' => \warm\renderer\Words::class,
		'password' => \warm\renderer\Password::class,
		'multiline-text' => \warm\renderer\MultilineText::class,
		'amis' => \warm\renderer\Component::class,
		'native-date' => \warm\renderer\TextControl::class,
		'native-time' => \warm\renderer\TextControl::class,
		'native-number' => \warm\renderer\TextControl::class,
		'code' => \warm\renderer\Code::class,
		'tooltip-wrapper' => \warm\renderer\TooltipWrapper::class,
	]));
	override(\warm\renderer\Expandable::type(0), map([
		'form' => \warm\renderer\Form::class,
		'alert' => \warm\renderer\Alert::class,
		'app' => \warm\renderer\Component::class,
		'audio' => \warm\renderer\Audio::class,
		'avatar' => \warm\renderer\Avatar::class,
		'button-group' => \warm\renderer\ButtonGroup::class,
		'breadcrumb' => \warm\renderer\Breadcrumb::class,
		'card' => \warm\renderer\Card::class,
		'card2' => \warm\renderer\Card2::class,
		'cards' => \warm\renderer\Cards::class,
		'carousel' => \warm\renderer\Carousel::class,
		'chart' => \warm\renderer\Chart::class,
		'calendar' => \warm\renderer\Calendar::class,
		'collapse' => \warm\renderer\Collapse::class,
		'collapse-group' => \warm\renderer\CollapseGroup::class,
		'color' => \warm\renderer\Color::class,
		'crud' => \warm\renderer\CRUDTable::class,
		'crud2' => \warm\renderer\CRUD2Table::class,
		'custom' => \warm\renderer\Custom::class,
		'date' => \warm\renderer\Date::class,
		'static-date' => \warm\renderer\StaticExactControl::class,
		'datetime' => \warm\renderer\Date::class,
		'static-datetime' => \warm\renderer\StaticExactControl::class,
		'time' => \warm\renderer\Date::class,
		'static-time' => \warm\renderer\StaticExactControl::class,
		'month' => \warm\renderer\Date::class,
		'static-month' => \warm\renderer\StaticExactControl::class,
		'date-range' => \warm\renderer\DateRange::class,
		'dialog' => \warm\renderer\Dialog::class,
		'spinner' => \warm\renderer\Spinner::class,
		'divider' => \warm\renderer\Divider::class,
		'dropdown-button' => \warm\renderer\DropdownButton::class,
		'drawer' => \warm\renderer\Drawer::class,
		'each' => \warm\renderer\Each::class,
		'flex' => \warm\renderer\Flex::class,
		'flex-item' => \warm\renderer\Component::class,
		'grid-2d' => \warm\renderer\Grid2D::class,
		'icon' => \warm\renderer\Icon::class,
		'iframe' => \warm\renderer\IFrame::class,
		'image' => \warm\renderer\Image::class,
		'static-image' => \warm\renderer\StaticExactControl::class,
		'images' => \warm\renderer\Images::class,
		'static-images' => \warm\renderer\Component::class,
		'json-schema' => \warm\renderer\Json::class,
		'json-schema-editor' => \warm\renderer\JSONSchemaEditorControl::class,
		'json' => \warm\renderer\Json::class,
		'static-json' => \warm\renderer\Component::class,
		'link' => \warm\renderer\Link::class,
		'list' => \warm\renderer\ListRenderer::class,
		'log' => \warm\renderer\Log::class,
		'static-list' => \warm\renderer\Component::class,
		'map' => \warm\renderer\Mapping::class,
		'mapping' => \warm\renderer\Mapping::class,
		'markdown' => \warm\renderer\Markdown::class,
		'nav' => \warm\renderer\Nav::class,
		'number' => \warm\renderer\Component::class,
		'page' => \warm\renderer\Page::class,
		'pagination' => \warm\renderer\Pagination::class,
		'pagination-wrapper' => \warm\renderer\PaginationWrapper::class,
		'property' => \warm\renderer\Property::class,
		'operation' => \warm\renderer\Operation::class,
		'plain' => \warm\renderer\Plain::class,
		'text' => \warm\renderer\Component::class,
		'progress' => \warm\renderer\Progress::class,
		'qrcode' => \warm\renderer\QRCode::class,
		'qr-code' => \warm\renderer\QRCode::class,
		'barcode' => \warm\renderer\Barcode::class,
		'remark' => \warm\renderer\Remark::class,
		'search-box' => \warm\renderer\SearchBox::class,
		'sparkline' => \warm\renderer\SparkLine::class,
		'status' => \warm\renderer\Status::class,
		'table' => \warm\renderer\Table::class,
		'static-table' => \warm\renderer\StaticExactControl::class,
		'table2' => \warm\renderer\TableSchema2::class,
		'html' => \warm\renderer\Html::class,
		'tpl' => \warm\renderer\Tpl::class,
		'tasks' => \warm\renderer\Tasks::class,
		'vbox' => \warm\renderer\VBox::class,
		'video' => \warm\renderer\Video::class,
		'wizard' => \warm\renderer\Wizard::class,
		'wrapper' => \warm\renderer\Wrapper::class,
		'web-component' => \warm\renderer\WebComponent::class,
		'anchor-nav' => \warm\renderer\AnchorNav::class,
		'steps' => \warm\renderer\Steps::class,
		'timeline' => \warm\renderer\Timeline::class,
		'control' => \warm\renderer\FormControl::class,
		'input-array' => \warm\renderer\ArrayControl::class,
		'button' => \warm\renderer\VanillaAction::class,
		'submit' => \warm\renderer\VanillaAction::class,
		'reset' => \warm\renderer\VanillaAction::class,
		'button-group-select' => \warm\renderer\ButtonGroupControl::class,
		'button-toolbar' => \warm\renderer\ButtonToolbar::class,
		'chained-select' => \warm\renderer\ChainedSelectControl::class,
		'chart-radios' => \warm\renderer\ChartRadios::class,
		'checkbox' => \warm\renderer\CheckboxControl::class,
		'checkboxes' => \warm\renderer\CheckboxesControl::class,
		'input-city' => \warm\renderer\InputCityControl::class,
		'input-color' => \warm\renderer\InputColorControl::class,
		'combo' => \warm\renderer\ComboControl::class,
		'condition-builder' => \warm\renderer\ConditionBuilderControl::class,
		'container' => \warm\renderer\Container::class,
		'switch-container' => \warm\renderer\SwitchContainer::class,
		'input-date' => \warm\renderer\DateControl::class,
		'input-datetime' => \warm\renderer\DateTimeControl::class,
		'input-time' => \warm\renderer\TimeControl::class,
		'input-quarter' => \warm\renderer\QuarterControl::class,
		'input-year' => \warm\renderer\YearControl::class,
		'input-month' => \warm\renderer\MonthControl::class,
		'input-date-range' => \warm\renderer\DateRangeControl::class,
		'input-time-range' => \warm\renderer\DateRangeControl::class,
		'input-datetime-range' => \warm\renderer\DateRangeControl::class,
		'input-excel' => \warm\renderer\InputExcel::class,
		'input-formula' => \warm\renderer\Component::class,
		'diff-editor' => \warm\renderer\DiffControl::class,
		'office-viewer' => \warm\renderer\Component::class,
		'pdf-viewer' => \warm\renderer\Component::class,
		'input-signature' => \warm\renderer\InputSignature::class,
		'editor' => \warm\renderer\EditorControl::class,
		'bat-editor' => \warm\renderer\EditorControl::class,
		'c-editor' => \warm\renderer\EditorControl::class,
		'coffeescript-editor' => \warm\renderer\EditorControl::class,
		'cpp-editor' => \warm\renderer\EditorControl::class,
		'csharp-editor' => \warm\renderer\EditorControl::class,
		'css-editor' => \warm\renderer\EditorControl::class,
		'dockerfile-editor' => \warm\renderer\EditorControl::class,
		'fsharp-editor' => \warm\renderer\EditorControl::class,
		'go-editor' => \warm\renderer\EditorControl::class,
		'handlebars-editor' => \warm\renderer\EditorControl::class,
		'html-editor' => \warm\renderer\EditorControl::class,
		'ini-editor' => \warm\renderer\EditorControl::class,
		'java-editor' => \warm\renderer\EditorControl::class,
		'javascript-editor' => \warm\renderer\EditorControl::class,
		'json-editor' => \warm\renderer\EditorControl::class,
		'less-editor' => \warm\renderer\EditorControl::class,
		'lua-editor' => \warm\renderer\EditorControl::class,
		'markdown-editor' => \warm\renderer\EditorControl::class,
		'msdax-editor' => \warm\renderer\EditorControl::class,
		'objective-c-editor' => \warm\renderer\EditorControl::class,
		'php-editor' => \warm\renderer\EditorControl::class,
		'plaintext-editor' => \warm\renderer\EditorControl::class,
		'postiats-editor' => \warm\renderer\EditorControl::class,
		'powershell-editor' => \warm\renderer\EditorControl::class,
		'pug-editor' => \warm\renderer\EditorControl::class,
		'python-editor' => \warm\renderer\EditorControl::class,
		'r-editor' => \warm\renderer\EditorControl::class,
		'razor-editor' => \warm\renderer\EditorControl::class,
		'ruby-editor' => \warm\renderer\EditorControl::class,
		'sb-editor' => \warm\renderer\EditorControl::class,
		'scss-editor' => \warm\renderer\EditorControl::class,
		'sol-editor' => \warm\renderer\EditorControl::class,
		'sql-editor' => \warm\renderer\EditorControl::class,
		'swift-editor' => \warm\renderer\EditorControl::class,
		'typescript-editor' => \warm\renderer\EditorControl::class,
		'vb-editor' => \warm\renderer\EditorControl::class,
		'xml-editor' => \warm\renderer\EditorControl::class,
		'yaml-editor' => \warm\renderer\EditorControl::class,
		'fieldset' => \warm\renderer\FieldSetControl::class,
		'fieldSet' => \warm\renderer\FieldSetControl::class,
		'input-file' => \warm\renderer\FileControl::class,
		'formula' => \warm\renderer\FormulaControl::class,
		'grid' => \warm\renderer\Grid::class,
		'group' => \warm\renderer\GroupControl::class,
		'hbox' => \warm\renderer\HBox::class,
		'hidden' => \warm\renderer\HiddenControl::class,
		'icon-picker' => \warm\renderer\IconPickerControl::class,
		'icon-select' => \warm\renderer\Component::class,
		'input-image' => \warm\renderer\ImageControl::class,
		'input-group' => \warm\renderer\InputGroupControl::class,
		'list-select' => \warm\renderer\ListControl::class,
		'location-picker' => \warm\renderer\LocationControl::class,
		'matrix-checkboxes' => \warm\renderer\MatrixControl::class,
		'input-month-range' => \warm\renderer\MonthRangeControl::class,
		'input-quarter-range' => \warm\renderer\QuarterRangeControl::class,
		'nested-select' => \warm\renderer\NestedSelectControl::class,
		'input-number' => \warm\renderer\NumberControl::class,
		'panel' => \warm\renderer\Panel::class,
		'picker' => \warm\renderer\PickerControl::class,
		'radio' => \warm\renderer\RadioControl::class,
		'radios' => \warm\renderer\RadiosControl::class,
		'input-range' => \warm\renderer\RangeControl::class,
		'input-rating' => \warm\renderer\RatingControl::class,
		'input-repeat' => \warm\renderer\RepeatControl::class,
		'input-rich-text' => \warm\renderer\RichTextControl::class,
		'select' => \warm\renderer\SelectControl::class,
		'service' => \warm\renderer\Service::class,
		'static' => \warm\renderer\StaticExactControl::class,
		'input-sub-form' => \warm\renderer\SubFormControl::class,
		'switch' => \warm\renderer\SwitchControl::class,
		'input-table' => \warm\renderer\TableControl::class,
		'tabs' => \warm\renderer\Tabs::class,
		'tabs-transfer' => \warm\renderer\TabsTransferControl::class,
		'input-tag' => \warm\renderer\TagControl::class,
		'input-text' => \warm\renderer\TextControl::class,
		'input-password' => \warm\renderer\TextControl::class,
		'input-email' => \warm\renderer\TextControl::class,
		'input-url' => \warm\renderer\TextControl::class,
		'uuid' => \warm\renderer\UUIDControl::class,
		'multi-select' => \warm\renderer\SelectControl::class,
		'textarea' => \warm\renderer\TextareaControl::class,
		'transfer' => \warm\renderer\TransferControl::class,
		'transfer-picker' => \warm\renderer\TransferPickerControl::class,
		'tabs-transfer-picker' => \warm\renderer\TabsTransferPickerControl::class,
		'input-tree' => \warm\renderer\TreeControl::class,
		'tree-select' => \warm\renderer\TreeSelectControl::class,
		'table-view' => \warm\renderer\TableView::class,
		'portlet' => \warm\renderer\Portlet::class,
		'grid-nav' => \warm\renderer\GridNav::class,
		'users-select' => \warm\renderer\UserSelectControl::class,
		'tag' => \warm\renderer\Tag::class,
		'tags' => \warm\renderer\Component::class,
		'words' => \warm\renderer\Words::class,
		'password' => \warm\renderer\Password::class,
		'multiline-text' => \warm\renderer\MultilineText::class,
		'amis' => \warm\renderer\Component::class,
		'native-date' => \warm\renderer\TextControl::class,
		'native-time' => \warm\renderer\TextControl::class,
		'native-number' => \warm\renderer\TextControl::class,
		'code' => \warm\renderer\Code::class,
		'tooltip-wrapper' => \warm\renderer\TooltipWrapper::class,
	]));
	expectedArguments(\warm\renderer\Action::actionType(), 0, 'ajax','link','url','drawer','dialog','confirm','cancel','prev','next','copy','close');
	expectedArguments(\warm\renderer\Action::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\AjaxAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\AjaxAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\AjaxAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\AjaxAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\Alert::level(), 0, 'info','warning','success','danger');
	expectedArguments(\warm\renderer\AnchorNav::direction(), 0, 'vertical','horizontal');
	expectedArguments(\warm\renderer\ArrayControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ArrayControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ArrayControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\ArrayControl::subFormMode(), 0, 'normal','horizontal','inline');
	expectedArguments(\warm\renderer\ArrayControl::tabsStyle(), 0, '','line','card','radio');
	expectedArguments(\warm\renderer\Avatar::crossOrigin(), 0, 'anonymous','use-credentials','');
	expectedArguments(\warm\renderer\Avatar::fit(), 0, 'fill','contain','cover','none','scale-down');
	expectedArguments(\warm\renderer\Avatar::shape(), 0, 'circle','square','rounded');
	expectedArguments(\warm\renderer\Badge::mode(), 0, 'text','dot','ribbon');
	expectedArguments(\warm\renderer\Badge::position(), 0, 'top-right','top-left','bottom-right','bottom-left');
	expectedArguments(\warm\renderer\BaseApi::dataType(), 0, 'json','form-data','form');
	expectedArguments(\warm\renderer\BaseApi::method(), 0, 'get','post','put','delete','patch','jsonp','js');
	expectedArguments(\warm\renderer\Button::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\Button::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\Button::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\Button::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\ButtonGroup::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\ButtonGroupControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ButtonGroupControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ButtonGroupControl::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\CRUD2Cards::loadType(), 0, 'more','pagination');
	expectedArguments(\warm\renderer\CRUD2List::loadType(), 0, 'more','pagination');
	expectedArguments(\warm\renderer\CRUD2List::size(), 0, 'sm','base');
	expectedArguments(\warm\renderer\CRUD2Table::loadType(), 0, 'more','pagination');
	expectedArguments(\warm\renderer\CRUD2Table::tableLayout(), 0, 'fixed','auto');
	expectedArguments(\warm\renderer\CRUDCards::orderDir(), 0, 'asc','desc');
	expectedArguments(\warm\renderer\CRUDList::orderDir(), 0, 'asc','desc');
	expectedArguments(\warm\renderer\CRUDList::size(), 0, 'sm','base');
	expectedArguments(\warm\renderer\CRUDTable::orderDir(), 0, 'asc','desc');
	expectedArguments(\warm\renderer\CRUDTable::tableLayout(), 0, 'fixed','auto');
	expectedArguments(\warm\renderer\Carousel::animation(), 0, 'fade','slide');
	expectedArguments(\warm\renderer\Carousel::controlsTheme(), 0, 'light','dark');
	expectedArguments(\warm\renderer\Carousel::thumbMode(), 0, 'contain','cover');
	expectedArguments(\warm\renderer\ChainedSelectControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ChainedSelectControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ChainedSelectControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\CheckboxControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\CheckboxControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\CheckboxControl::optionType(), 0, 'default','button');
	expectedArguments(\warm\renderer\CheckboxControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\CheckboxesControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\CheckboxesControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\CheckboxesControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Code::language(), 0, 'bat','c','coffeescript','cpp','csharp','css','dockerfile','fsharp','go','handlebars','html','ini','java','javascript','json','less','lua','markdown','msdax','objective-c','php','plaintext','postiats','powershell','pug','python','r','razor','ruby','sb','scss','shell','sol','sql','swift','typescript','vb','xml','yaml');
	expectedArguments(\warm\renderer\Collapse::headerPosition(), 0, 'top','bottom');
	expectedArguments(\warm\renderer\Collapse::size(), 0, 'xs','sm','md','lg','base');
	expectedArguments(\warm\renderer\CollapseGroup::expandIconPosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\ComboControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ComboControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ComboControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\ComboControl::subFormMode(), 0, 'normal','horizontal','inline');
	expectedArguments(\warm\renderer\ComboControl::tabsStyle(), 0, '','line','card','radio');
	expectedArguments(\warm\renderer\ConditionBuilderControl::builderMode(), 0, 'simple','full');
	expectedArguments(\warm\renderer\ConditionBuilderControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ConditionBuilderControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ConditionBuilderControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\ConditionGroupValue::conjunction(), 0, 'and','or');
	expectedArguments(\warm\renderer\CopyAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\CopyAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\CopyAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\CopyAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\Date::type(), 0, 'date','datetime','time','static-date','static-datetime','static-time');
	expectedArguments(\warm\renderer\DateControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\DateControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\DateControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\DateControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\DateRangeControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\DateRangeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\DateRangeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\DateRangeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\DateRangeControl::type(), 0, 'input-date-range','input-datetime-range','input-time-range');
	expectedArguments(\warm\renderer\DateTimeControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\DateTimeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\DateTimeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\DateTimeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Dialog::size(), 0, 'xs','sm','md','lg','xl','full');
	expectedArguments(\warm\renderer\DialogAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\DialogAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\DialogAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\DialogAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\DiffControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\DiffControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\DiffControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Divider::direction(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\Divider::lineStyle(), 0, 'dashed','solid');
	expectedArguments(\warm\renderer\Divider::titlePosition(), 0, 'left','center','right');
	expectedArguments(\warm\renderer\Drawer::position(), 0, 'left','right','top','bottom');
	expectedArguments(\warm\renderer\Drawer::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\DrawerAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\DrawerAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\DrawerAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\DrawerAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\DropdownButton::align(), 0, 'left','right');
	expectedArguments(\warm\renderer\DropdownButton::level(), 0, 'info','success','danger','warning','primary','link');
	expectedArguments(\warm\renderer\DropdownButton::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\DropdownButton::trigger(), 0, 'click','hover');
	expectedArguments(\warm\renderer\EditorControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\EditorControl::language(), 0, 'bat','c','coffeescript','cpp','csharp','css','dockerfile','fsharp','go','handlebars','html','ini','java','javascript','json','less','lua','markdown','msdax','objective-c','php','plaintext','postiats','powershell','pug','python','r','razor','ruby','sb','scss','shell','sol','sql','swift','typescript','vb','xml','yaml');
	expectedArguments(\warm\renderer\EditorControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\EditorControl::size(), 0, 'sm','md','lg','xl','xxl');
	expectedArguments(\warm\renderer\EditorControl::type(), 0, 'editor','bat-editor','c-editor','coffeescript-editor','cpp-editor','csharp-editor','css-editor','dockerfile-editor','fsharp-editor','go-editor','handlebars-editor','html-editor','ini-editor','java-editor','javascript-editor','json-editor','less-editor','lua-editor','markdown-editor','msdax-editor','objective-c-editor','php-editor','plaintext-editor','postiats-editor','powershell-editor','pug-editor','python-editor','r-editor','razor-editor','ruby-editor','sb-editor','scss-editor','sol-editor','sql-editor','swift-editor','typescript-editor','vb-editor','xml-editor','yaml-editor');
	expectedArguments(\warm\renderer\EmailAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\EmailAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\EmailAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\EmailAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\FeedbackDialog::size(), 0, 'xs','sm','md','lg','xl','full');
	expectedArguments(\warm\renderer\FieldSetControl::headerPosition(), 0, 'top','bottom');
	expectedArguments(\warm\renderer\FieldSetControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\FieldSetControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\FieldSetControl::size(), 0, 'xs','sm','md','lg','base');
	expectedArguments(\warm\renderer\FieldSetControl::subFormMode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\FieldSetControl::titlePosition(), 0, 'top','bottom');
	expectedArguments(\warm\renderer\FieldSetControl::type(), 0, 'fieldset','fieldSet');
	expectedArguments(\warm\renderer\FileControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\FileControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\FileControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Flex::alignContent(), 0, 'normal','flex-start','flex-end','center','space-between','space-around','space-evenly','stretch');
	expectedArguments(\warm\renderer\Flex::alignItems(), 0, 'stretch','start','flex-start','flex-end','end','center','baseline');
	expectedArguments(\warm\renderer\Flex::direction(), 0, 'row','column','row-reverse','column-reverse');
	expectedArguments(\warm\renderer\Flex::justify(), 0, 'start','flex-start','center','end','flex-end','space-around','space-between','space-evenly');
	expectedArguments(\warm\renderer\Form::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\Form::mode(), 0, 'normal','inline','horizontal','flex');
	expectedArguments(\warm\renderer\FormControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\FormControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\FormControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\FormulaControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\FormulaControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\FormulaControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Grid::align(), 0, 'left','right','between','center');
	expectedArguments(\warm\renderer\Grid::gap(), 0, 'xs','sm','base','none','md','lg');
	expectedArguments(\warm\renderer\Grid::valign(), 0, 'top','middle','bottom','between');
	expectedArguments(\warm\renderer\GridColumn::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\GridColumn::valign(), 0, 'top','middle','bottom','between');
	expectedArguments(\warm\renderer\GridNav::direction(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\GroupControl::direction(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\GroupControl::gap(), 0, 'xs','sm','normal');
	expectedArguments(\warm\renderer\GroupControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\GroupControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\GroupControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\GroupControl::subFormMode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\HBox::align(), 0, 'left','right','between','center');
	expectedArguments(\warm\renderer\HBox::gap(), 0, 'xs','sm','base','none','md','lg');
	expectedArguments(\warm\renderer\HBox::subFormMode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\HBox::valign(), 0, 'top','middle','bottom','between');
	expectedArguments(\warm\renderer\HBoxColumn::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\HBoxColumn::valign(), 0, 'top','middle','bottom','between');
	expectedArguments(\warm\renderer\HiddenControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\HiddenControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\HiddenControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Html::type(), 0, 'tpl','html');
	expectedArguments(\warm\renderer\IFrame::referrerpolicy(), 0, 'no-referrer','no-referrer-when-downgrade','origin','origin-when-cross-origin','same-origin','strict-origin','strict-origin-when-cross-origin','unsafe-url');
	expectedArguments(\warm\renderer\Icon::vendor(), 0, 'iconfont','fa','');
	expectedArguments(\warm\renderer\IconPickerControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\IconPickerControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\IconPickerControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Image::imageMode(), 0, 'thumb','original');
	expectedArguments(\warm\renderer\Image::thumbMode(), 0, 'w-full','h-full','contain','cover');
	expectedArguments(\warm\renderer\Image::thumbRatio(), 0, '1:1','4:3','16:9');
	expectedArguments(\warm\renderer\Image::type(), 0, 'image','static-image');
	expectedArguments(\warm\renderer\ImageControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ImageControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ImageControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\ImageControl::thumbMode(), 0, 'w-full','h-full','contain','cover');
	expectedArguments(\warm\renderer\ImageControl::thumbRatio(), 0, '1:1','4:3','16:9');
	expectedArguments(\warm\renderer\ImageToolbarAction::key(), 0, 'ROTATE_RIGHT','ROTATE_LEFT','ZOOM_IN','ZOOM_OUT','SCALE_ORIGIN');
	expectedArguments(\warm\renderer\Images::thumbMode(), 0, 'w-full','h-full','contain','cover');
	expectedArguments(\warm\renderer\Images::thumbRatio(), 0, '1:1','4:3','16:9');
	expectedArguments(\warm\renderer\Images::type(), 0, 'images','static-images');
	expectedArguments(\warm\renderer\InputCityControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\InputCityControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\InputCityControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\InputColorControl::format(), 0, 'hex','rgb','rgba','hsl');
	expectedArguments(\warm\renderer\InputColorControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\InputColorControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\InputColorControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\InputGroupControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\InputGroupControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\InputGroupControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\InputSignature::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\InputSignature::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\InputSignature::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\JSONSchemaEditorControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\JSONSchemaEditorControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\JSONSchemaEditorControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Json::iconStyle(), 0, 'square','circle','triangle');
	expectedArguments(\warm\renderer\Json::type(), 0, 'json','static-json');
	expectedArguments(\warm\renderer\LinkAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\LinkAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\LinkAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\LinkAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\ListControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\ListControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\ListControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\ListItem::actionsPosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\ListRenderer::size(), 0, 'sm','base');
	expectedArguments(\warm\renderer\ListRenderer::type(), 0, 'list','static-list');
	expectedArguments(\warm\renderer\ListenerAction::dataMergeMode(), 0, 'merge','override');
	expectedArguments(\warm\renderer\LocationControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\LocationControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\LocationControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\LocationControl::vendor(), 0, 'baidu','gaode','tenxun');
	expectedArguments(\warm\renderer\Log::operation(), 0, 'stop','clear','showLineNumber','filter');
	expectedArguments(\warm\renderer\Mapping::type(), 0, 'map','mapping');
	expectedArguments(\warm\renderer\MatrixControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\MatrixControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\MatrixControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\MonthControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\MonthControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\MonthControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\MonthControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\MonthRangeControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\MonthRangeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\MonthRangeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\MonthRangeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Nav::mode(), 0, 'float','inline');
	expectedArguments(\warm\renderer\Nav::stacked(), 0, '1','');
	expectedArguments(\warm\renderer\Nav::themeColor(), 0, 'light','dark');
	expectedArguments(\warm\renderer\NestedSelectControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\NestedSelectControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\NestedSelectControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\NestedSelectControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\NumberControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\NumberControl::displayMode(), 0, 'base','enhance');
	expectedArguments(\warm\renderer\NumberControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\NumberControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\NumberControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\OtherAction::actionType(), 0, 'prev','next','cancel','close','submit','confirm','add','reset','reset-and-submit');
	expectedArguments(\warm\renderer\OtherAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\OtherAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\OtherAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\OtherAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\Pagination::mode(), 0, 'simple','normal');
	expectedArguments(\warm\renderer\PaginationWrapper::position(), 0, 'top','bottom','none');
	expectedArguments(\warm\renderer\Panel::subFormMode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\PickerControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\PickerControl::modalMode(), 0, 'dialog','drawer');
	expectedArguments(\warm\renderer\PickerControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\PickerControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Plain::type(), 0, 'plain','text');
	expectedArguments(\warm\renderer\Portlet::tabsMode(), 0, '','line','card','radio','vertical','tiled');
	expectedArguments(\warm\renderer\PortletTab::iconPosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\Progress::gapPosition(), 0, 'top','bottom','left','right');
	expectedArguments(\warm\renderer\Progress::mode(), 0, 'line','circle','dashboard');
	expectedArguments(\warm\renderer\Property::mode(), 0, 'table','simple');
	expectedArguments(\warm\renderer\QRCode::level(), 0, 'L','M','Q','H');
    expectedArguments(\warm\renderer\QRCode::mode(), 0, 'canvas','svg');
	expectedArguments(\warm\renderer\QRCode::type(), 0, 'qrcode','qr-code');
	expectedArguments(\warm\renderer\QuarterControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\QuarterControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\QuarterControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\QuarterControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\QuarterRangeControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\QuarterRangeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\QuarterRangeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\QuarterRangeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RadioControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RadioControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RadioControl::optionType(), 0, 'default','button');
	expectedArguments(\warm\renderer\RadioControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RadiosControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RadiosControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RadiosControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RangeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RangeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RangeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RangeControl::tooltipPlacement(), 0, 'auto','top','right','bottom','left');
	expectedArguments(\warm\renderer\RatingControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RatingControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RatingControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RatingControl::textPosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\ReloadAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\ReloadAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\ReloadAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\ReloadAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\Remark::placement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\Remark::shape(), 0, 'circle','square');
	expectedArguments(\warm\renderer\RepeatControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RepeatControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RepeatControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RichTextControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\RichTextControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\RichTextControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\RichTextControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\RichTextControl::vendor(), 0, 'froala','tinymce');
	expectedArguments(\warm\renderer\SchemaApi::dataType(), 0, 'json','form-data','form');
	expectedArguments(\warm\renderer\SchemaApi::method(), 0, 'get','post','put','delete','patch','jsonp','js');
	expectedArguments(\warm\renderer\SchemaPopOver::mode(), 0, 'dialog','drawer','popOver');
	expectedArguments(\warm\renderer\SchemaPopOver::position(), 0, 'center','left-top','left-top-left-top','left-top-left-center','left-top-left-bottom','left-top-center-top','left-top-center-center','left-top-center-bottom','left-top-right-top','left-top-right-center','left-top-right-bottom','right-top','right-top-left-top','right-top-left-center','right-top-left-bottom','right-top-center-top','right-top-center-center','right-top-center-bottom','right-top-right-top','right-top-right-center','right-top-right-bottom','left-bottom','left-bottom-left-top','left-bottom-left-center','left-bottom-left-bottom','left-bottom-center-top','left-bottom-center-center','left-bottom-center-bottom','left-bottom-right-top','left-bottom-right-center','left-bottom-right-bottom','right-bottom','right-bottom-left-top','right-bottom-left-center','right-bottom-left-bottom','right-bottom-center-top','right-bottom-center-center','right-bottom-center-bottom','right-bottom-right-top','right-bottom-right-center','right-bottom-right-bottom','fixed-center','fixed-left-top','fixed-right-top','fixed-left-bottom','fixed-right-bottom');
	expectedArguments(\warm\renderer\SchemaPopOver::size(), 0, 'sm','md','lg','xl');
	expectedArguments(\warm\renderer\SchemaPopOver::trigger(), 0, 'click','hover');
	expectedArguments(\warm\renderer\SelectControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\SelectControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\SelectControl::leftMode(), 0, 'tree','list');
	expectedArguments(\warm\renderer\SelectControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\SelectControl::rightMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\SelectControl::searchResultMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\SelectControl::selectMode(), 0, 'table','group','tree','chained','associated');
	expectedArguments(\warm\renderer\SelectControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\SelectControl::type(), 0, 'select','multi-select');
	expectedArguments(\warm\renderer\Spinner::size(), 0, 'sm','lg','');
	expectedArguments(\warm\renderer\Spinner::tipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\StaticExactControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\StaticExactControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\StaticExactControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\StaticExactControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Steps::labelPlacement(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\Steps::mode(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\SubFormControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\SubFormControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\SubFormControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\SwitchControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\SwitchControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\SwitchControl::size(), 0, 'sm','md');
	expectedArguments(\warm\renderer\Tab::iconPosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\Tab::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\Table::tableLayout(), 0, 'fixed','auto');
	expectedArguments(\warm\renderer\Table::type(), 0, 'table','static-table');
	expectedArguments(\warm\renderer\TableColumn::align(), 0, 'left','right','center','justify');
	expectedArguments(\warm\renderer\TableColumn::breakpoint(), 0, '*','xs','sm','md','lg');
	expectedArguments(\warm\renderer\TableColumn::fixed(), 0, 'left','right','none');
	expectedArguments(\warm\renderer\TableControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TableControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TableControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TableControl::tableLayout(), 0, 'fixed','auto');
	expectedArguments(\warm\renderer\TableSchema2::tableLayout(), 0, 'fixed','auto');
	expectedArguments(\warm\renderer\Tabs::sidePosition(), 0, 'left','right');
	expectedArguments(\warm\renderer\Tabs::subFormMode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\Tabs::tabsMode(), 0, '','line','card','radio','vertical','chrome','simple','strong','tiled','sidebar');
	expectedArguments(\warm\renderer\TabsTransferControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TabsTransferControl::leftMode(), 0, 'tree','list');
	expectedArguments(\warm\renderer\TabsTransferControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TabsTransferControl::rightMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TabsTransferControl::searchResultMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TabsTransferControl::selectMode(), 0, 'table','list','tree','chained','associated');
	expectedArguments(\warm\renderer\TabsTransferControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::leftMode(), 0, 'tree','list');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::rightMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::searchResultMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::selectMode(), 0, 'table','list','tree','chained','associated');
	expectedArguments(\warm\renderer\TabsTransferPickerControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Tag::displayMode(), 0, 'normal','rounded','status');
	expectedArguments(\warm\renderer\TagControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TagControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TagControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TextControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\TextControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TextControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TextControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TextControl::type(), 0, 'input-text','input-email','input-url','input-password','native-date','native-time','native-number');
	expectedArguments(\warm\renderer\TextareaControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\TextareaControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TextareaControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TextareaControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TimeControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\TimeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TimeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TimeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\Timeline::direction(), 0, 'horizontal','vertical');
	expectedArguments(\warm\renderer\Timeline::mode(), 0, 'left','right','alternate');
	expectedArguments(\warm\renderer\Toast::position(), 0, 'top-right','top-center','top-left','bottom-center','bottom-left','bottom-right','center 可选值: top-right','top-center','top-left','bottom-center','bottom-left','bottom-right','center');
	expectedArguments(\warm\renderer\ToastAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\ToastAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\ToastAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\ToastAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\TooltipWrapper::placement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\TooltipWrapper::tooltipTheme(), 0, 'light','dark');
	expectedArguments(\warm\renderer\Tpl::type(), 0, 'tpl','html');
	expectedArguments(\warm\renderer\TransferControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TransferControl::leftMode(), 0, 'tree','list');
	expectedArguments(\warm\renderer\TransferControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TransferControl::rightMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TransferControl::searchResultMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TransferControl::selectMode(), 0, 'table','list','tree','chained','associated');
	expectedArguments(\warm\renderer\TransferControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TransferPickerControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\TransferPickerControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TransferPickerControl::leftMode(), 0, 'tree','list');
	expectedArguments(\warm\renderer\TransferPickerControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TransferPickerControl::pickerSize(), 0, 'xs','sm','md','lg','xl','full');
	expectedArguments(\warm\renderer\TransferPickerControl::rightMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TransferPickerControl::searchResultMode(), 0, 'table','list','tree','chained');
	expectedArguments(\warm\renderer\TransferPickerControl::selectMode(), 0, 'table','list','tree','chained','associated');
	expectedArguments(\warm\renderer\TransferPickerControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TreeControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TreeControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TreeControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\TreeSelectControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\TreeSelectControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\TreeSelectControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\UUIDControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\UUIDControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\UUIDControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\UrlAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\UrlAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\UrlAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\UrlAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\UserSelectControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\UserSelectControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\UserSelectControl::size(), 0, 'xs','sm','md','lg','full');
	expectedArguments(\warm\renderer\VanillaAction::level(), 0, 'info','success','warning','danger','link','primary','dark','light','secondary');
	expectedArguments(\warm\renderer\VanillaAction::size(), 0, 'xs','sm','md','lg');
	expectedArguments(\warm\renderer\VanillaAction::tooltipPlacement(), 0, 'top','right','bottom','left');
	expectedArguments(\warm\renderer\VanillaAction::type(), 0, 'button','submit','reset');
	expectedArguments(\warm\renderer\Video::aspectRatio(), 0, 'auto','4:3','16:9');
	expectedArguments(\warm\renderer\Wizard::mode(), 0, 'vertical','horizontal');
	expectedArguments(\warm\renderer\WizardStep::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\WizardStep::mode(), 0, 'normal','inline','horizontal','flex');
	expectedArguments(\warm\renderer\Wrapper::size(), 0, 'xs','sm','md','lg','none');
	expectedArguments(\warm\renderer\YearControl::borderMode(), 0, 'full','half','none');
	expectedArguments(\warm\renderer\YearControl::labelAlign(), 0, 'right','left','top','inherit');
	expectedArguments(\warm\renderer\YearControl::mode(), 0, 'normal','inline','horizontal');
	expectedArguments(\warm\renderer\YearControl::size(), 0, 'xs','sm','md','lg','full');
}
